Added caching of pofiles
Seluj78/Potodo pull request #68
Opened 2020-09-16 06:56 UTC by Seluj78

2020-09-16 06:56 UTC, pep8speaks commented
Hello @Seluj78! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:



* In the file [`potodo/potodo.py`](https://github.com/Seluj78/Potodo/blob/695fa16cd1a0e67b158fd420a1e796888815b44a/potodo/potodo.py):

> [Line 133:1](https://github.com/Seluj78/Potodo/blob/695fa16cd1a0e67b158fd420a1e796888815b44a/potodo/potodo.py#L133): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace

2020-10-08 20:59 UTC, JulienPalard commented on potodo/_cache.py
> +) -> Optional[Tuple[datetime, dict]]:
À première vue c'est plutôt un `Tuple[Optional[datetime], Optional[dict]]` ou un `Union[Tuple[None, None], Tuple[datetime, dict]]`

2020-10-08 21:03 UTC, JulienPalard commented on potodo/potodo.py
> +            if dt_expiry < datetime.utcnow():
Est-ce que ça ne serait pas plus lisible de bouger ce if dans `_get_cache_file_content` ? Elle renverai ainsi soit `None` soit `data`. Et ce serait plus symétrique car c'est `_set_cache_file_content` qui stocke cette date.

2020-10-08 21:05 UTC, JulienPalard commented
If you want to avoid displaying stale cache (which would happen if you `git pull` between two invocations of potodo), you could store the mtime of the file when it's cached, and compare the mtime of the file when it's read: if the mtime is different, the file has changed it should be read again.

2020-10-12 06:52 UTC, Seluj78 commented
> If you want to avoid displaying stale cache (which would happen if you `git pull` between two invocations of potodo), you could store the mtime of the file when it's cached, and compare the mtime of the file when it's read: if the mtime is different, the file has changed it should be read again.

The problem is, I store the raw `po_files_and_dirs` dictionnary, which i then directly used in the rest of the process. See https://github.com/Seluj78/Potodo/pull/68/files#diff-0dc0200b5c248313b31e1a7f9570054dR169

That would mean adding another layer of running through the files and directories one by one and adding their `mtime` manually to the dict somewhere and then removing it when the cache is validated

2020-10-12 07:48 UTC, JulienPalard commented
> The problem is, I store the raw `po_files_and_dirs` dictionnary, which i then directly used in the rest of the process. See https://github.com/Seluj78/Potodo/pull/68/files#diff-0dc0200b5c248313b31e1a7f9570054dR169

I didn't said it was straightforward :p

I think it still could be done, in `get_po_files_from_repo`, when you create each `PoFileStats(po_file)`, you could have a
 "if is in cache and mtime not changed, get from cache, else compute and cache" thing.

So out of `get_po_files_from_repo` you can have a mixed set from both the cache and fresh data, instead of it being all white or all black.

2020-10-12 11:05 UTC, Seluj78 commented
NICE
`potodo -p /Users/seluj78/Projects/python-docs-fr --no-cache  4.97s user 0.56s system 75% cpu 7.321 total`
`potodo -p /Users/seluj78/Projects/python-docs-fr  2.26s user 0.49s system 68% cpu 4.008 total`

2020-10-12 12:05 UTC, JulienPalard requested changes
LGTM with nits.

2020-10-12 12:05 UTC, JulienPalard commented on potodo/potodo.py
> +        help="Disables cache (Cache is disabled when files are modified in git)",
```suggestion
        help="Disables cache (Cache is disabled when files are modified)",
```

2020-10-12 12:05 UTC, JulienPalard commented on tox.ini
> +commands = black --check --diff tests/ potodo/ --line-length 88
```suggestion
commands = black --check --diff tests/ potodo/
```
Not needed, 88 is the default.

2020-10-12 12:05 UTC, JulienPalard commented on potodo/potodo.py
> +    :param no_cache: Disables cache (Cache is disabled when files are modified in git)
```suggestion
    :param no_cache: Disables cache (Cache is disabled when files are modified)
```

2020-10-12 12:08 UTC, JulienPalard approved these changes

2020-10-12 12:09 UTC, merged